name: Create Dev Releases

on:
  push:
    branches:
      - main
      - edge
      - 'preview-**'

jobs:
  package:
    uses: ./.github/workflows/pkg-binary.yml
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-x64
          - linux-arm64
          - macos-x64
          - macos-arm64
          - windows-x64
    with:
      filename: devtool-${{ matrix.target }}-${{ github.sha }}
      target: ${{ matrix.target }}
      version: dev

  sign:
    uses: ./.github/workflows/sign-binary.yml
    needs:
      - package
    strategy:
      fail-fast: false
      matrix:
        file:
          - devtool-linux-x64-${{ github.sha }}
          - devtool-macos-x64-${{ github.sha }}
          # @TODO: @reynoldsalec needs to investiage keylocker authentication failures
          # - devtool-windows-x64-${{ github.sha }}
          - devtool-linux-arm64-${{ github.sha }}
          - devtool-macos-arm64-${{ github.sha }}
    with:
      download-pattern: packaged-devtool-*
      file: ${{ matrix.file }}
    secrets:
      apple-notary-user: ${{ secrets.APPLE_NOTARY_USER }}
      apple-notary-password: ${{ secrets.APPLE_NOTARY_PASSWORD }}
      certificate-data: ${{ contains(matrix.file, 'macos') && secrets.APPLE_CERT_DATA || secrets.KEYLOCKER_CLIENT_CERT }}
      certificate-password: ${{ contains(matrix.file, 'macos') && secrets.APPLE_CERT_PASSWORD || secrets.KEYLOCKER_CLIENT_CERT_PASSWORD }}
      keylocker-api-key: ${{ secrets.KEYLOCKER_API_KEY }}
      keylocker-cert-sha1-hash: ${{ secrets.KEYLOCKER_CERT_SHA1_HASH }}
      keylocker-keypair-alias: ${{ secrets.KEYLOCKER_KEYPAIR_ALIAS }}

  rename-release-binary-branch:
    uses: ./.github/workflows/release-rename-binary.yml
    needs:
      - sign
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-x64
          - macos-x64
          # - windows-x64
          - linux-arm64
          - macos-arm64

    with:
      source: devtool-${{ matrix.target }}-${{ github.sha }}
      destination: devtool-${{ matrix.target }}-${{ github.head_ref || github.ref_name }}
      download-pattern: signed-devtool-*

  checksum:
    uses: ./.github/workflows/generate-checksums.yml
    strategy:
      fail-fast: false
      matrix:
        alias:
          - ${{ github.head_ref || github.ref_name }}
          - ${{ github.sha }}
    needs:
      - rename-release-binary-branch
    with:
      download-pattern: release-*
      flatten: true
      output: sha256sum-${{ matrix.alias }}.txt
      show: true
      upload-name: release-checksums-${{ matrix.alias }}

  deploy-releases-s3:
    uses: ./.github/workflows/deploy-s3.yml
    needs:
      - checksum
    with:
      download-pattern: release-*
    secrets:
      aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
      aws-region: us-east-1
  deploy-releases-artifacts:
    uses: ./.github/workflows/deploy-artifacts.yml
    needs:
      - checksum
    with:
      download-pattern: release-*
