name: Run Docs Tests

on:
  pull_request:

jobs:
  docs-tests:
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache version builds
        uses: actions/cache@v4
        with:
          key: lando-mvb-docs
          path: docs/.vitepress/cache/@lando/mvb
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install
      - name: Run linter
        run: bun run lint
      - name: Test mvb
        run: bun run docs:mvb
      - name: Test build
        run: bun run docs:build
